### PR TITLE
Update UAA release to v27 (bosh) and 3.12.0 (source)

### PR DESCRIPTION
**Pull request by rogeruiz**
Reflects some of the work outlined [here in Favro](https://favro.com/card/1e11108a2da81e3bd7153a7a/18F-3580).

### CODE REVIEW

**Comment by rogeruiz** [comment]
Still waiting on the updates coming in from 18F/cg-uaa#40 around alert messaging for EW environment. cc @rememberlenny

**Comment by rogeruiz** [comment]
~~No longer a `[ work in progress ]` but I'm blocked on whether I should wait for 18F/cg-uaa#40 or just deploy twice?~~ Not waiting. We're gonna :shipit:

**Comment by rogeruiz** [comment]
~~Almost completely forgot the spec. on it.~~ Specs in there now. Ready to :shipit: @jmcarp.

**Review by jmcarp — APPROVED** [review]

**Comment by rogeruiz** [comment]
Weird. Not sure what happened here, but I'm curious to hear what could have happened here? Is this related to previously relying on the EW `bosh-blobstore`? I had to upload these to get built in GC.

```
2017-03-10 20:19:34   11163253 928a8aca-a8f0-4036-aa0c-804c463fc895
2017-03-10 20:20:01   75550921 a1a61854-e783-4265-928c-d66d8baf5eb6
2017-03-10 20:20:36   77696717 a59fd9c0-1b4f-408d-b73f-19262dfa85a3
2017-03-10 20:21:04    9304967 b24b05a0-e6e8-4ce4-9391-e0345158bf00
2017-03-10 20:22:38       1909 fc5d2a42-126c-477c-7280-17a385771ec7
2017-03-10 20:23:31    3681863 5d0b04c6-3afd-479a-7be2-06ed566c3197
2017-03-10 20:26:18   15627638 41307768-6032-4651-6111-885c976a3e78
2017-03-10 20:30:07       1086 1de332b9-6a6f-416f-6d13-73e33763e6f2
2017-03-10 20:32:07      25385 a9c19428-ce71-45b4-5337-a617fb8843ca
2017-03-10 20:32:07  146889533 fc6cb7db-8b4f-4e48-5af5-63d969906279
```

**Pull request merged**
